/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package farma;

import database.CInventario_ADMIN;
import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class AGREGAR_PRODUCTO_INVENTARIO extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AGREGAR_PRODUCTO_INVENTARIO.class.getName());

    /**
     * Creates new form AGREGAR_PRODUCTO_INVENTARIO
     */
    public AGREGAR_PRODUCTO_INVENTARIO() {
        initComponents();
        setSize(800, 600); // ancho, alto
        txt_categoria.setVisible(false);
        txt_proveedor.setVisible(false);
        
        setLocationRelativeTo(null); // centrar ventana
        database.CInventario_ADMIN admin = new CInventario_ADMIN();
        admin.MostrarProveedoresCombo(cb_proveedor);
        admin.MostrarCategoriasCombo(cb_categoria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JTextField();
        lbl_descripción = new javax.swing.JTextField();
        lbl_preciocompra = new javax.swing.JTextField();
        lbl_precioventa = new javax.swing.JTextField();
        lbl_stockingresante = new javax.swing.JTextField();
        lbl_stockminimo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbl_codigoProducto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cb_categoria = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cb_proveedor = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        txt_categoria = new javax.swing.JTextField();
        txt_proveedor = new javax.swing.JTextField();
        jchoser = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(658, 110));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("INGRESAR PRODUCTOS");
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("NOMBRE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setText("DESCRIPCIÓN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setText("PRECIO DE COMPRA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setText("PRECIO DE VENTA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setText("STOCK INGRESANTE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setText("STOCK MÍNIMO TOLERADO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanel2.add(jLabel7, gridBagConstraints);

        lbl_nombre.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel2.add(lbl_nombre, gridBagConstraints);

        lbl_descripción.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel2.add(lbl_descripción, gridBagConstraints);

        lbl_preciocompra.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        jPanel2.add(lbl_preciocompra, gridBagConstraints);

        lbl_precioventa.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        jPanel2.add(lbl_precioventa, gridBagConstraints);

        lbl_stockingresante.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        jPanel2.add(lbl_stockingresante, gridBagConstraints);

        lbl_stockminimo.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        jPanel2.add(lbl_stockminimo, gridBagConstraints);

        jLabel8.setText("CÓDIGO DEL PRODUCTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel8, gridBagConstraints);

        lbl_codigoProducto.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(lbl_codigoProducto, gridBagConstraints);

        jLabel9.setText("ESTABLECE SU CATEGORIA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel9, gridBagConstraints);

        cb_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_categoria.setPreferredSize(new java.awt.Dimension(208, 26));
        cb_categoria.addItemListener(this::cb_categoriaItemStateChanged);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel2.add(cb_categoria, gridBagConstraints);

        jLabel10.setText("ELIGE EL PROVEEDOR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel10, gridBagConstraints);

        cb_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cb_proveedor.setPreferredSize(new java.awt.Dimension(208, 26));
        cb_proveedor.addItemListener(this::cb_proveedorItemStateChanged);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        jPanel2.add(cb_proveedor, gridBagConstraints);

        jButton1.setText("Guardar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        jPanel2.add(jButton1, gridBagConstraints);

        txt_categoria.setText("jTextField1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel2.add(txt_categoria, gridBagConstraints);

        txt_proveedor.setText("jTextField2");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        jPanel2.add(txt_proveedor, gridBagConstraints);

        jchoser.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        jPanel2.add(jchoser, gridBagConstraints);

        jLabel11.setText("ESTABLECE FECHA DE VENCIMIENTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        jPanel2.add(jLabel11, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_categoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_categoriaItemStateChanged
        database.CInventario_ADMIN admin = new CInventario_ADMIN();
        admin.MostrarIdPorCategorias(cb_categoria, txt_categoria);
    }//GEN-LAST:event_cb_categoriaItemStateChanged

    private void cb_proveedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_proveedorItemStateChanged
        database.CInventario_ADMIN admin = new CInventario_ADMIN();
        admin.MostrarIdPorProveedores(cb_proveedor, txt_proveedor);
    }//GEN-LAST:event_cb_proveedorItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(lbl_codigoProducto.getText().trim().isEmpty() ||
       lbl_nombre.getText().trim().isEmpty() ||
       lbl_descripción.getText().trim().isEmpty() ||
       lbl_preciocompra.getText().trim().isEmpty() ||
       lbl_precioventa.getText().trim().isEmpty() ||
       lbl_stockingresante.getText().trim().isEmpty() ||
       lbl_stockminimo.getText().trim().isEmpty()){

        JOptionPane.showMessageDialog(this,
                "Complete todos los campos.",
                "Validación",
                JOptionPane.WARNING_MESSAGE);
        return;
    }
        if(jchoser.getDate() == null){
        JOptionPane.showMessageDialog(this,
                "Seleccione una fecha de vencimiento.",
                "Validación",
                JOptionPane.WARNING_MESSAGE);
        return;
    }
        try {

        double precioCompra =
                Double.parseDouble(lbl_preciocompra.getText());

        double precioVenta =
                Double.parseDouble(lbl_precioventa.getText());

        int stockIngresante =
                Integer.parseInt(lbl_stockingresante.getText());

        int stockMinimo =
                Integer.parseInt(lbl_stockminimo.getText());

        int idCategoria =
                Integer.parseInt(txt_categoria.getText());

        int idProveedor =
                Integer.parseInt(txt_proveedor.getText());

        // Validar positivos
        if (precioCompra <= 0) {
            JOptionPane.showMessageDialog(this,
                    "El precio de compra debe ser mayor que 0.");
            return;
        }

        if (precioVenta <= 0) {
            JOptionPane.showMessageDialog(this,
                    "El precio de venta debe ser mayor que 0.");
            return;
        }

        if (stockIngresante < 0) {
            JOptionPane.showMessageDialog(this,
                    "El stock ingresante no puede ser negativo.");
            return;
        }

        if (stockMinimo < 0) {
            JOptionPane.showMessageDialog(this,
                    "El stock mínimo no puede ser negativo.");
            return;
        }

        if (idCategoria <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Categoría inválida.");
            return;
        }

        if (idProveedor <= 0) {
            JOptionPane.showMessageDialog(this,
                    "Proveedor inválido.");
            return;
        }

        // Regla de negocio
        if (precioVenta < precioCompra) {
            JOptionPane.showMessageDialog(this,
                    "El precio de venta no puede ser menor que el precio de compra.");
            return;
        }
        
        java.util.Date fechautil = jchoser.getDate();
        java.sql.Date fechasql = new java.sql.Date(fechautil.getTime());
        database.CInventario_ADMIN admin = new CInventario_ADMIN();
        admin.GuardarProductos(lbl_codigoProducto, lbl_nombre, lbl_descripción, lbl_preciocompra, lbl_stockingresante, txt_categoria, txt_proveedor, lbl_precioventa, lbl_stockminimo, fechasql);
        lbl_codigoProducto.setText("");
        lbl_nombre.setText("");
        lbl_descripción.setText("");
        lbl_preciocompra.setText("");
        lbl_precioventa.setText("");
        lbl_stockingresante.setText("");
        lbl_stockminimo.setText("");
        jchoser.setDate(null);
        }
        catch (NumberFormatException e){
            JOptionPane.showMessageDialog(this,
                "Verifique que los precios, stocks, categoría y proveedor sean números válidos.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AGREGAR_PRODUCTO_INVENTARIO().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_categoria;
    private javax.swing.JComboBox<String> cb_proveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jchoser;
    private javax.swing.JTextField lbl_codigoProducto;
    private javax.swing.JTextField lbl_descripción;
    private javax.swing.JTextField lbl_nombre;
    private javax.swing.JTextField lbl_preciocompra;
    private javax.swing.JTextField lbl_precioventa;
    private javax.swing.JTextField lbl_stockingresante;
    private javax.swing.JTextField lbl_stockminimo;
    private javax.swing.JTextField txt_categoria;
    private javax.swing.JTextField txt_proveedor;
    // End of variables declaration//GEN-END:variables
}
