/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package farma;
import database.CInventario_ADMIN;
import java.sql.Date;

/**
 *
 * @author manue
 */
public class MODIFICAR_PRODUCTO_INVENTARIO extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MODIFICAR_PRODUCTO_INVENTARIO.class.getName());

    /**
     * Creates new form MODIFICAR_PRODUCTO_INVENTARIO
     */
    public MODIFICAR_PRODUCTO_INVENTARIO() {
        initComponents();
        setSize(800, 600); // ancho, alto
        txt_idcateogira.setVisible(false);
        txt_idproveedor.setVisible(false);
        System.out.println(
        "Editable: "
        + txt_precio_compra.isEditable());

System.out.println(
        "Enabled: "
        + txt_precio_compra.isEnabled());
        database.CInventario_ADMIN admin = new CInventario_ADMIN();
        admin.MostrarCategoriasCombo(combo_categoria);
        admin.MostrarProveedoresCombo(combo_proveedor);
        
        
    }
    public void RecibirDatos(String codigo,String nombre, String descripcion, String categoria,String precio_compra, String precio_venta, java.sql.Date fecha_vencimiento,String stock_actual, String stock_minimo,String proveedor){
        txt_codigo.setText(codigo);
        txt_nombre.setText(nombre);
        txt_descripcion.setText(descripcion);
        combo_categoria.setSelectedItem(categoria);
        txt_precio_compra.setText(precio_compra);
        txt_precio_venta.setText(precio_venta);
        jchoser.setDate(fecha_vencimiento);
        txt_stock.setText(stock_actual);
        txt_stockminimo.setText(stock_minimo);
        combo_proveedor.setSelectedItem(proveedor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_stock = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jchoser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        combo_categoria = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        combo_proveedor = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        txt_precio_venta = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txt_stockminimo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txt_idcateogira = new javax.swing.JTextField();
        txt_idproveedor = new javax.swing.JTextField();
        txt_precio_compra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(658, 389));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1034, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("CÓDIGO DEL PRODUCTO");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        txt_codigo.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(txt_codigo, gridBagConstraints);

        jLabel2.setText("NOMBRE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel2, gridBagConstraints);

        txt_nombre.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel2.add(txt_nombre, gridBagConstraints);

        jLabel3.setText("DESCRIPCIÓN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel3, gridBagConstraints);

        txt_descripcion.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel2.add(txt_descripcion, gridBagConstraints);

        jLabel4.setText("PRECIO DE COMPRA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setText("STOCK INGRESANTE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel2.add(jLabel5, gridBagConstraints);

        txt_stock.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        jPanel2.add(txt_stock, gridBagConstraints);

        jLabel6.setText("ESTABLECE FECHA DE VENCIMIENTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        jPanel2.add(jLabel6, gridBagConstraints);

        jchoser.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        jPanel2.add(jchoser, gridBagConstraints);

        jLabel7.setText("ESTABLECE SU CATEGORIA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel7, gridBagConstraints);

        combo_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_categoria.setPreferredSize(new java.awt.Dimension(208, 26));
        combo_categoria.addItemListener(this::combo_categoriaItemStateChanged);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel2.add(combo_categoria, gridBagConstraints);

        jLabel8.setText("ELIGE EL PROVEEDOR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel8, gridBagConstraints);

        combo_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_proveedor.setPreferredSize(new java.awt.Dimension(208, 26));
        combo_proveedor.addItemListener(this::combo_proveedorItemStateChanged);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel2.add(combo_proveedor, gridBagConstraints);

        jLabel9.setText("PRECIO DE VENTA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel9, gridBagConstraints);

        txt_precio_venta.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        jPanel2.add(txt_precio_venta, gridBagConstraints);

        jLabel10.setText("STOCK MÍNIMO TOLERADO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel10, gridBagConstraints);

        txt_stockminimo.setPreferredSize(new java.awt.Dimension(208, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        jPanel2.add(txt_stockminimo, gridBagConstraints);

        jButton1.setText("MODIFICAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        jPanel2.add(jButton1, gridBagConstraints);

        txt_idcateogira.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(txt_idcateogira, gridBagConstraints);

        txt_idproveedor.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel2.add(txt_idproveedor, gridBagConstraints);

        txt_precio_compra.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        jPanel2.add(txt_precio_compra, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_categoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_categoriaItemStateChanged
        database.CInventario_ADMIN admin = new CInventario_ADMIN();
        admin.MostrarIdPorCategorias(combo_categoria, txt_idcateogira);
    }//GEN-LAST:event_combo_categoriaItemStateChanged

    private void combo_proveedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_proveedorItemStateChanged
        database.CInventario_ADMIN admin = new CInventario_ADMIN();
        admin.MostrarIdPorProveedores(combo_proveedor, txt_idproveedor);
    }//GEN-LAST:event_combo_proveedorItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        java.util.Date fechautil = jchoser.getDate();
        java.sql.Date fechasql = new java.sql.Date(fechautil.getTime());
        database.CInventario_ADMIN admin = new CInventario_ADMIN();
        admin.ModificarProductos(txt_codigo, txt_nombre, txt_descripcion, txt_precio_compra, txt_stock, txt_idcateogira, txt_idproveedor, txt_precio_venta, txt_stockminimo, fechasql);
        this.dispose();      
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MODIFICAR_PRODUCTO_INVENTARIO().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_categoria;
    private javax.swing.JComboBox<String> combo_proveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jchoser;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_idcateogira;
    private javax.swing.JTextField txt_idproveedor;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_precio_compra;
    private javax.swing.JTextField txt_precio_venta;
    private javax.swing.JTextField txt_stock;
    private javax.swing.JTextField txt_stockminimo;
    // End of variables declaration//GEN-END:variables
}
