/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package farma;

/**
 *
 * @author jhonlyjuniorgarciapitoy
 */
public class registrarCliente extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(registrarCliente.class.getName());

    /**
     * Creates new form registrarCliente
     */
    public registrarCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDniReg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombreReg = new javax.swing.JTextField();
        txtTelefonoReg = new javax.swing.JTextField();
        txtCorreoReg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("DNI / RUC:");

        jLabel2.setText("Nombre Completo :");

        jLabel3.setText("Teléfono (Opcional):");

        jLabel4.setText("Correo (Opcional):");

        txtNombreReg.addActionListener(this::txtNombreRegActionPerformed);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Guardar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel5.setText("Registrar Cliente ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1)
                        .addComponent(jLabel4)))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCorreoReg)
                    .addComponent(txtTelefonoReg)
                    .addComponent(txtNombreReg)
                    .addComponent(txtDniReg))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDniReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTelefonoReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCorreoReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreRegActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
                                             
    String dni = txtDniReg.getText().trim();
    String nombre = txtNombreReg.getText().trim();
    String telefono = txtTelefonoReg.getText().trim();
    String correo = txtCorreoReg.getText().trim();
    
    // 1. VALIDACIÓN DEL DNI (Solo números y exactamente 8 dígitos)
    // El formato "\\d{8}" significa: estrictamente 8 caracteres numéricos
    if (!dni.matches("\\d{8}")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El DNI debe contener exactamente 8 números.");
        return;
    }
    
    // 2. VALIDACIÓN DEL NOMBRE (Solo letras y espacios, no se permiten números)
    if (nombre.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "El Nombre Completo es obligatorio.");
        return;
    }
    // El formato "^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$" permite letras de la A a la Z, tildes y espacios
    if (!nombre.matches("^[a-zA-ZáéíóúÁÉÍÓÚñÑ ]+$")) {
        javax.swing.JOptionPane.showMessageDialog(this, "El Nombre Completo solo debe contener letras.");
        return;
    }
    
    // 3. VALIDACIÓN DEL TELÉFONO (Opcional, pero si se pone, deben ser 9 números iniciando con 9)
    if (!telefono.isEmpty()) {
        if (!telefono.matches("9\\d{8}")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El teléfono debe ser un número celular válido de 9 dígitos (debe empezar con 9).");
            return;
        }
    }
    
    // 4. VALIDACIÓN DEL CORREO (Opcional, pero si se pone, debe tener formato válido con @ y .)
    if (!correo.isEmpty()) {
        if (!correo.contains("@") || !correo.contains(".")) {
            javax.swing.JOptionPane.showMessageDialog(this, "El formato del correo electrónico no es válido (ejemplo@dominio.com).");
            return;
        }
    }
    
    // --- SI PASA TODAS LAS VALIDACIONES, SE GUARDA EN LA BASE DE DATOS ---
    database.Conexion con = new database.Conexion();
    java.sql.Connection cn = con.conectar();
    
    if (cn != null) {
        try {
            String sql = "INSERT INTO Clientes (dni_ruc, nombre_completo, telefono, correo) VALUES (?, ?, ?, ?)";
            java.sql.PreparedStatement pst = cn.prepareStatement(sql, java.sql.Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, dni);
            pst.setString(2, nombre);
            pst.setString(3, telefono.isEmpty() ? null : telefono);
            pst.setString(4, correo.isEmpty() ? null : correo);
            
            pst.executeUpdate();
            
            java.sql.ResultSet generadoKeys = pst.getGeneratedKeys();
            int idGenerado = 0;
            if (generadoKeys.next()) {
                idGenerado = generadoKeys.getInt(1);
            }
            
            cn.close();
            
            // Guardamos en la mochila de la pantalla de ventas
            farma.ventas pantallaVentas = farma.ventas.getInstancia();
            pantallaVentas.clienteActual.idCliente = idGenerado;
            pantallaVentas.clienteActual.dniRuc = dni;
            pantallaVentas.clienteActual.nombreCompleto = nombre;
            pantallaVentas.clienteActual.telefono = telefono;
            pantallaVentas.clienteActual.correo = correo;
            
            javax.swing.JOptionPane.showMessageDialog(this, "¡Cliente registrado con éxito!");
            this.dispose(); 
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al guardar en BD: " + e.getMessage());
        }
     }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                registrarCliente dialog = new registrarCliente(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCorreoReg;
    public javax.swing.JTextField txtDniReg;
    private javax.swing.JTextField txtNombreReg;
    private javax.swing.JTextField txtTelefonoReg;
    // End of variables declaration//GEN-END:variables
}
