/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas_Admin;

import database.DAOInventario_admin;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author manue
 */
public class AGREGAR_PRODUCTOS_ADMIN extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AGREGAR_PRODUCTOS_ADMIN.class.getName());

    /**
     * Creates new form AGREGAR_PRODUCTOS_ADMIN
     */
    public AGREGAR_PRODUCTOS_ADMIN() {
        initComponents();
        database.DAOInventario_admin conectar = new DAOInventario_admin();
        conectar.MostrarCategoriasCombo(combo_categoria);
        conectar.MostrarProveedoresCombo(combo_proveedores);
        txt_id_proveedor.setVisible(false);
        txt_idcategoria.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_codigoproducto = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_stockactual = new javax.swing.JTextField();
        txt_stockminimo = new javax.swing.JTextField();
        txt_preciodecompra = new javax.swing.JTextField();
        txt_preciodeventa = new javax.swing.JTextField();
        txt_id_proveedor = new javax.swing.JTextField();
        txt_idcategoria = new javax.swing.JTextField();
        jchoser = new com.toedter.calendar.JDateChooser();
        combo_proveedores = new javax.swing.JComboBox<>();
        combo_categoria = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(641, 120));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("GUARDAR PRODUCTOS");
        jPanel1.add(jLabel11, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Codigo Producto");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Descripción");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setText("Seleccione la categoría");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setText("Seleccione el proveedor");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setText("Precio de venta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Precio de compra");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel8.setText("Vecha de vencimiento");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel9.setText("Stock Actual");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel2.add(jLabel9, gridBagConstraints);

        jLabel10.setText("Stock Minimo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanel2.add(jLabel10, gridBagConstraints);

        txt_codigoproducto.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(txt_codigoproducto, gridBagConstraints);

        txt_nombre.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel2.add(txt_nombre, gridBagConstraints);

        txt_descripcion.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel2.add(txt_descripcion, gridBagConstraints);

        txt_stockactual.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        jPanel2.add(txt_stockactual, gridBagConstraints);

        txt_stockminimo.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        jPanel2.add(txt_stockminimo, gridBagConstraints);

        txt_preciodecompra.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        jPanel2.add(txt_preciodecompra, gridBagConstraints);

        txt_preciodeventa.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        jPanel2.add(txt_preciodeventa, gridBagConstraints);

        txt_id_proveedor.setText("jTextField8");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(txt_id_proveedor, gridBagConstraints);

        txt_idcategoria.setText("jTextField9");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel2.add(txt_idcategoria, gridBagConstraints);

        jchoser.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        jPanel2.add(jchoser, gridBagConstraints);

        combo_proveedores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_proveedores.setPreferredSize(new java.awt.Dimension(200, 26));
        combo_proveedores.addItemListener(this::combo_proveedoresItemStateChanged);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel2.add(combo_proveedores, gridBagConstraints);

        combo_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_categoria.setPreferredSize(new java.awt.Dimension(200, 26));
        combo_categoria.addItemListener(this::combo_categoriaItemStateChanged);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel2.add(combo_categoria, gridBagConstraints);

        jButton1.setText("GUARDAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        jPanel2.add(jButton1, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_proveedoresItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_proveedoresItemStateChanged
        DAOInventario_admin conectar = new DAOInventario_admin();
        conectar.MostrarIdPorProveedores(combo_proveedores, txt_id_proveedor);
    }//GEN-LAST:event_combo_proveedoresItemStateChanged

    private void combo_categoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_categoriaItemStateChanged
        DAOInventario_admin conectar = new DAOInventario_admin();
        conectar.MostrarIdPorCategorias(combo_categoria, txt_idcategoria);
    }//GEN-LAST:event_combo_categoriaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    // Validar campos vacíos
    if(txt_codigoproducto.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese el código del producto");
        txt_codigoproducto.requestFocus();
        return;
    }

    if(txt_nombre.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese el nombre del producto");
        txt_nombre.requestFocus();
        return;
    }

    if(txt_descripcion.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese la descripción del producto");
        txt_descripcion.requestFocus();
        return;
    }

    if(txt_preciodecompra.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese el precio de compra");
        txt_preciodecompra.requestFocus();
        return;
    }

    if(txt_preciodeventa.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese el precio de venta");
        txt_preciodeventa.requestFocus();
        return;
    }

    if(txt_stockactual.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese el stock actual");
        txt_stockactual.requestFocus();
        return;
    }

    if(txt_stockminimo.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Ingrese el stock mínimo");
        txt_stockminimo.requestFocus();
        return;
    }

    if(txt_idcategoria.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Seleccione una categoría");
        return;
    }

    if(txt_id_proveedor.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(null, "Seleccione un proveedor");
        return;
    }

    // Validar fecha
    if(jchoser.getDate() == null){
        JOptionPane.showMessageDialog(null, "Seleccione una fecha de vencimiento");
        return;
    }

    // Validar números
    double precioCompra;
    double precioVenta;
    int stockActual;
    int stockMinimo;

    try{
        precioCompra = Double.parseDouble(txt_preciodecompra.getText().trim());
    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null, "Precio de compra inválido");
        txt_preciodecompra.requestFocus();
        return;
    }

    try{
        precioVenta = Double.parseDouble(txt_preciodeventa.getText().trim());
    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null, "Precio de venta inválido");
        txt_preciodeventa.requestFocus();
        return;
    }

    try{
        stockActual = Integer.parseInt(txt_stockactual.getText().trim());
    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null, "Stock actual inválido");
        txt_stockactual.requestFocus();
        return;
    }

    try{
        stockMinimo = Integer.parseInt(txt_stockminimo.getText().trim());
    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null, "Stock mínimo inválido");
        txt_stockminimo.requestFocus();
        return;
    }

    // Validaciones de negocio
    if(precioCompra <= 0){
        JOptionPane.showMessageDialog(null, "El precio de compra debe ser mayor a 0");
        return;
    }

    if(precioVenta <= 0){
        JOptionPane.showMessageDialog(null, "El precio de venta debe ser mayor a 0");
        return;
    }

    if(precioVenta <= precioCompra){
        JOptionPane.showMessageDialog(null,
                "El precio de venta debe ser mayor al precio de compra");
        return;
    }

    if(stockActual < 0){
        JOptionPane.showMessageDialog(null,
                "El stock actual no puede ser negativo");
        return;
    }

    if(stockMinimo < 0){
        JOptionPane.showMessageDialog(null,
                "El stock mínimo no puede ser negativo");
        return;
    }   
        Date mFecha = jchoser.getDate();
        java.sql.Date fecha_sql = new java.sql.Date(mFecha.getTime());
        DAOInventario_admin conectar = new DAOInventario_admin();
        conectar.GuardarProductos(txt_codigoproducto, txt_nombre, txt_descripcion, txt_preciodecompra, txt_stockactual, txt_idcategoria, txt_id_proveedor, txt_preciodeventa, txt_stockminimo, fecha_sql);
        txt_codigoproducto.setText("");
        txt_nombre.setText("");
        txt_descripcion.setText("");
        txt_preciodecompra.setText("");
        txt_preciodeventa.setText("");
        txt_stockactual.setText("");
        txt_stockminimo.setText("");
        jchoser.setDate(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AGREGAR_PRODUCTOS_ADMIN().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_categoria;
    private javax.swing.JComboBox<String> combo_proveedores;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jchoser;
    private javax.swing.JTextField txt_codigoproducto;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_id_proveedor;
    private javax.swing.JTextField txt_idcategoria;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_preciodecompra;
    private javax.swing.JTextField txt_preciodeventa;
    private javax.swing.JTextField txt_stockactual;
    private javax.swing.JTextField txt_stockminimo;
    // End of variables declaration//GEN-END:variables
}
