/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas_Admin;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author manue
 */
public class MENU_INVENTARIO extends javax.swing.JPanel {

    /**
     * Creates new form MENU_INVENTARIO
     */
    public MENU_INVENTARIO() {
        initComponents();
    }
private void MostrarPanel(JPanel p){
        p.setSize(823, 748);
        p.setLocation(0, 0);
        
        jPanel2.removeAll();
        jPanel2.add(p, BorderLayout.CENTER);
        jPanel2.revalidate();
        jPanel2.repaint();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(893, 50));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("CATALOGO DE PRODUCTOS");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new java.awt.GridBagConstraints());

        jButton2.setText("LOTES");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel1.add(jButton2, new java.awt.GridBagConstraints());

        jButton3.setText("jButton3");
        jPanel1.add(jButton3, new java.awt.GridBagConstraints());

        jButton4.setText("jButton4");
        jPanel1.add(jButton4, new java.awt.GridBagConstraints());

        jButton5.setText("jButton5");
        jPanel1.add(jButton5, new java.awt.GridBagConstraints());

        jButton6.setText("jButton6");
        jPanel1.add(jButton6, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(903, 521));
        jPanel2.setLayout(new java.awt.BorderLayout());
        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    Pantallas_Admin.CONTROL_INVENTARIO_ADMIN listar = new CONTROL_INVENTARIO_ADMIN();
    MostrarPanel(listar);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CONTROL_LOTES_INVENTARIO listar = new CONTROL_LOTES_INVENTARIO();
        MostrarPanel(listar);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
