/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas_Admin;

import database.DAOInventario_admin;
import java.util.Date;

/**
 *
 * @author manue
 */
public class MODIFICAR_PRODUCTOS_ADMINS extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MODIFICAR_PRODUCTOS_ADMINS.class.getName());

    /**
     * Creates new form MODIFICAR_PRODUCTOS_ADMINS
     */
    public MODIFICAR_PRODUCTOS_ADMINS() {
        initComponents();
        DAOInventario_admin conectar = new DAOInventario_admin();
        conectar.MostrarCategoriasCombo(combo_categoria);
        conectar.MostrarProveedoresCombo(combo_proveedor);
        txt_id_categoria.setVisible(false);
        txt_id_proveedor.setVisible(false);
    }
    public void RecibirProducto(String codigo, String nombre, String descripcion, String categoria, String proveedor, String precio_compra, String precio_venta, java.sql.Date fecha, String stock_actual, String stock_minimo){
        txt_codigo.setText(codigo);
        txt_nombre.setText(nombre);
        txt_descripcion.setText(descripcion);
        combo_categoria.setSelectedItem(categoria);
        combo_proveedor.setSelectedItem(proveedor);
        txt_preciodecompra.setText(precio_compra);
        txt_preciodeventa.setText(precio_venta);
        jchoser.setDate(fecha);
        txt_stockactual.setText(stock_actual);
        txt_stockminimo.setText(stock_minimo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        txt_descripcion = new javax.swing.JTextField();
        txt_preciodeventa = new javax.swing.JTextField();
        txt_preciodecompra = new javax.swing.JTextField();
        txt_stockminimo = new javax.swing.JTextField();
        combo_proveedor = new javax.swing.JComboBox<>();
        combo_categoria = new javax.swing.JComboBox<>();
        txt_id_proveedor = new javax.swing.JTextField();
        txt_id_categoria = new javax.swing.JTextField();
        jchoser = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txt_stockactual = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("MODIFICAR PRODUCTO");
        jPanel1.add(jLabel11, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("CODIGO PRODUCTO");
        jPanel2.add(jLabel1, new java.awt.GridBagConstraints());

        jLabel2.setText("NOMBRE");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel2, gridBagConstraints);

        jLabel3.setText("DESCRIPCION");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel3, gridBagConstraints);

        jLabel4.setText("FECHA DE VENCIMIENTO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel4, gridBagConstraints);

        jLabel5.setText("SELECCIONE PROVEEDOR");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel2.add(jLabel5, gridBagConstraints);

        jLabel6.setText("SELECCIONE CATEGORIA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        jPanel2.add(jLabel6, gridBagConstraints);

        jLabel7.setText("PRECIO DE VENTA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel2.add(jLabel7, gridBagConstraints);

        jLabel8.setText("PRECIO DE COMPRA");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        jPanel2.add(jLabel8, gridBagConstraints);

        jLabel9.setText("STOCK MINIMO");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        jPanel2.add(jLabel9, gridBagConstraints);

        txt_codigo.setEditable(false);
        txt_codigo.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(txt_codigo, gridBagConstraints);

        txt_nombre.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        jPanel2.add(txt_nombre, gridBagConstraints);

        txt_descripcion.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        jPanel2.add(txt_descripcion, gridBagConstraints);

        txt_preciodeventa.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        jPanel2.add(txt_preciodeventa, gridBagConstraints);

        txt_preciodecompra.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        jPanel2.add(txt_preciodecompra, gridBagConstraints);

        txt_stockminimo.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 9;
        jPanel2.add(txt_stockminimo, gridBagConstraints);

        combo_proveedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_proveedor.setPreferredSize(new java.awt.Dimension(200, 26));
        combo_proveedor.addItemListener(this::combo_proveedorItemStateChanged);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        jPanel2.add(combo_proveedor, gridBagConstraints);

        combo_categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo_categoria.setPreferredSize(new java.awt.Dimension(200, 26));
        combo_categoria.addItemListener(this::combo_categoriaItemStateChanged);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        jPanel2.add(combo_categoria, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        jPanel2.add(txt_id_proveedor, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        jPanel2.add(txt_id_categoria, gridBagConstraints);

        jchoser.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        jPanel2.add(jchoser, gridBagConstraints);

        jLabel10.setText("STOCK ACTUAL");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        jPanel2.add(jLabel10, gridBagConstraints);

        txt_stockactual.setPreferredSize(new java.awt.Dimension(200, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        jPanel2.add(txt_stockactual, gridBagConstraints);

        jButton1.setText("MODIFICAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        jPanel2.add(jButton1, gridBagConstraints);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo_proveedorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_proveedorItemStateChanged
        DAOInventario_admin conectar = new DAOInventario_admin();
        conectar.MostrarIdPorProveedores(combo_proveedor, txt_id_proveedor);
    }//GEN-LAST:event_combo_proveedorItemStateChanged

    private void combo_categoriaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_categoriaItemStateChanged
        DAOInventario_admin conectar = new DAOInventario_admin();
        conectar.MostrarIdPorCategorias(combo_categoria, txt_id_categoria);
    }//GEN-LAST:event_combo_categoriaItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DAOInventario_admin conectar = new DAOInventario_admin();
        Date mFecha = jchoser.getDate();
        long fecha = mFecha.getTime();
        java.sql.Date fecha_sql = new java.sql.Date(fecha);
        conectar.ModificarProductos(txt_codigo, txt_nombre, txt_descripcion, txt_preciodecompra, txt_stockactual, txt_id_categoria, txt_id_proveedor, txt_preciodeventa, txt_stockminimo,fecha_sql);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MODIFICAR_PRODUCTOS_ADMINS().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_categoria;
    private javax.swing.JComboBox<String> combo_proveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser jchoser;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_id_categoria;
    private javax.swing.JTextField txt_id_proveedor;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_preciodecompra;
    private javax.swing.JTextField txt_preciodeventa;
    private javax.swing.JTextField txt_stockactual;
    private javax.swing.JTextField txt_stockminimo;
    // End of variables declaration//GEN-END:variables
}
