/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas_Admin;

import dao.DAOLotes_inventario_admin;
import javax.swing.JOptionPane;
import model.SesionUsuario;
import model.Usuario;
import model.entidad_producto_inventario;
import model.entidad_proveedor_inventario;

/**
 *
 * @author manue
 */
public class VISUALIZADOR_LOTES_X_PRODUCTO extends javax.swing.JPanel {

    /**
     * Creates new form VISUALIZADOR_LOTES_X_PRODUCTO
     */
    int idloteSeleccionado = 0;
    private Usuario usuario;
    public VISUALIZADOR_LOTES_X_PRODUCTO() {
        initComponents();
        DAOLotes_inventario_admin conectar = new DAOLotes_inventario_admin();
        conectar.llamar_productos(combo_producto);
        conectar.llamar_proveedores(combo_proveedor);
        usuario = SesionUsuario.getUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        combo_producto = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        combo_proveedor = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1038, 200));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(1038, 50));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("BUSCAR POR PRODUCTOS");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel3.add(jButton1, new java.awt.GridBagConstraints());

        jButton2.setText("BUSCAR POR PROVEEDORES");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        jPanel3.add(jButton2, new java.awt.GridBagConstraints());

        jButton3.setText("BUSCAR POR PRODUCTO Y PROVEEDOR");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel3.add(jButton3, new java.awt.GridBagConstraints());

        jButton5.setText("BUSCAR PRODUCTOS VENCIDOS");
        jButton5.addActionListener(this::jButton5ActionPerformed);
        jPanel3.add(jButton5, new java.awt.GridBagConstraints());

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setPreferredSize(new java.awt.Dimension(1038, 80));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jLabel2.setText("SELECCIONA EL PRODUCTO DESEADO");
        jPanel4.add(jLabel2, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.ipady = 4;
        jPanel4.add(combo_producto, gridBagConstraints);

        jLabel1.setText("SELECCIONA EL PROVEEDOR DESEADO");
        jPanel4.add(jLabel1, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 84;
        gridBagConstraints.ipady = 4;
        jPanel4.add(combo_proveedor, gridBagConstraints);

        jButton4.setText("BUSCAR");
        jButton4.addActionListener(this::jButton4ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel4.add(jButton4, gridBagConstraints);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 20;
        jPanel4.add(jPanel5, gridBagConstraints);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel6.setPreferredSize(new java.awt.Dimension(1038, 100));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel6.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        combo_proveedor.setEnabled(false);
        combo_producto.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        combo_producto.setEnabled(false);
        combo_proveedor.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        combo_proveedor.setEnabled(true);
        combo_producto.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        DAOLotes_inventario_admin consulta = new DAOLotes_inventario_admin();
        consulta.ListarLotes_Vencidos(jTable1);
        combo_producto.setEnabled(false);
        combo_proveedor.setEnabled(false);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        DAOLotes_inventario_admin consulta = new DAOLotes_inventario_admin();
        if (combo_producto.isEnabled() && !combo_proveedor.isEnabled()){
            entidad_producto_inventario producto = (entidad_producto_inventario) combo_producto.getSelectedItem();
            if(producto != null){
                consulta.ListarLotes_x_producto(jTable1, producto.getId_producto());
            }
            else{
                JOptionPane.showMessageDialog(null, "Seleccione un producto válido.");
            }
        }
        else if (!combo_producto.isEnabled() && combo_proveedor.isEnabled()){
            entidad_proveedor_inventario proveedor = (entidad_proveedor_inventario) combo_proveedor.getSelectedItem();
            if(proveedor != null){
                consulta.ListarLotes_x_proveedor(jTable1, proveedor.getId_proveedor());
            }
            else{
                JOptionPane.showMessageDialog(null, "Seleccione un proveedor válido.");
            }
        }
        else if(combo_producto.isEnabled() && combo_proveedor.isEnabled()){
            entidad_producto_inventario producto = (entidad_producto_inventario) combo_producto.getSelectedItem();
            entidad_proveedor_inventario proveedor = (entidad_proveedor_inventario) combo_proveedor.getSelectedItem();
            if(producto != null && proveedor != null){
                consulta.ListarLotes_x_producto_Y_proveedor(jTable1, producto.getId_producto(), proveedor.getId_proveedor());
            }
            else{
                JOptionPane.showMessageDialog(null, "Seleccione un producto y proveedor válido.");
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "Ambos filtros están desactivados. Presione el botón de activar ambos.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if(fila >= 0){
            idloteSeleccionado = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<entidad_producto_inventario> combo_producto;
    private javax.swing.JComboBox<entidad_proveedor_inventario> combo_proveedor;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
