/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas_Admin;

import dao.DAOLotes_inventario_admin;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author manue
 */
public class VISUALIZADOR_LOTES_REGISTROMOVIMIENTOS extends javax.swing.JPanel {

    /**
     * Creates new form VISUALIZADOR_LOTES_REGISTROMOVIMIENTOS
     */
    public VISUALIZADOR_LOTES_REGISTROMOVIMIENTOS() {
        initComponents();
    }
    private void MostrarPanel(JPanel p){
        p.setSize(823, 748);
        p.setLocation(0, 0);
        
        jPanel3.removeAll();
        jPanel3.setLayout(new java.awt.BorderLayout());  
        jPanel3.add(p, BorderLayout.CENTER);
        jPanel3.revalidate();
        jPanel3.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones de Busqueda"));
        jPanel2.setPreferredSize(new java.awt.Dimension(939, 120));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jButton1.setText("LISTAR TODOS LOS MOVIMIENTOS REGISTRADOS");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        jPanel2.add(jButton1, gridBagConstraints);

        jButton2.setText("BUSCAR MOVIMIENTOS SEGÚN RANGO DE FECHAS");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        jPanel2.add(jButton2, gridBagConstraints);

        jButton3.setText("BUSCAR MOVIMIENTOS SEGÚN PRODUCTO");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        jPanel2.add(jButton3, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(20, 40, 20, 40));
        jPanel3.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VISUALIZAR_TODOS_REGISTROS panel = new VISUALIZAR_TODOS_REGISTROS();
        MostrarPanel(panel);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        VISUALIZADOR_REGISTROS_X_PRODUCTO panel = new VISUALIZADOR_REGISTROS_X_PRODUCTO();
        MostrarPanel(panel);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VISUALIZADOR_REGISTROS_X_FECHAS panel = new VISUALIZADOR_REGISTROS_X_FECHAS();
        MostrarPanel(panel);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
