/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas_Admin;

import dao.DAOLotes_inventario_admin;
import javax.swing.JOptionPane;
import model.SesionUsuario;
import model.Usuario;
import model.acción_registro_movimiento_lotesinventario;

/**
 *
 * @author manue
 */
public class VISUALIZADOR_LOTES_X_GENERALES extends javax.swing.JPanel {

    /**
     * Creates new form VISUALIZADOR_LOTES_X_GENERALES
     */
    private Usuario usuario;
    public VISUALIZADOR_LOTES_X_GENERALES() {
        initComponents();
        dao.DAOLotes_inventario_admin conectar = new DAOLotes_inventario_admin();
        conectar.Listarlotes(jTable1);
        
        usuario = SesionUsuario.getUsuario();
        stock_nuevo.setEnabled(false);
    }
    private int idloteSeleccionado = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        stock_act = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        stock_nuevo = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jPanel2.setPreferredSize(new java.awt.Dimension(1500, 800));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 700;
        gridBagConstraints.ipady = 100;
        jPanel2.add(jScrollPane1, gridBagConstraints);

        jLabel2.setText("INGRESA LOS DÍAS PARA VISUALIZAR LOTES PROXIMOS A VENCER");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel2.add(jLabel2, gridBagConstraints);

        jTextField2.setPreferredSize(new java.awt.Dimension(90, 26));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 4;
        jPanel2.add(jTextField2, gridBagConstraints);

        jButton5.setText("LISTAR");
        jButton5.setPreferredSize(new java.awt.Dimension(100, 27));
        jButton5.addActionListener(this::jButton5ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel2.add(jButton5, gridBagConstraints);

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 10));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.ipady = 5;
        jPanel2.add(jPanel4, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("ID LOTE SELECCIONADO:");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 36));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel1, gridBagConstraints);

        id.setPreferredSize(new java.awt.Dimension(100, 36));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 7;
        jPanel1.add(id, gridBagConstraints);

        jLabel3.setText("STOCK REGISTRADO: ");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 36));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        jPanel1.add(jLabel3, gridBagConstraints);

        stock_act.setPreferredSize(new java.awt.Dimension(100, 36));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        jPanel1.add(stock_act, gridBagConstraints);

        jLabel4.setText("STOCK NUEVO (RECUENTO): ");
        jLabel4.setPreferredSize(new java.awt.Dimension(165, 36));
        jLabel4.setRequestFocusEnabled(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel1.add(jLabel4, gridBagConstraints);

        stock_nuevo.setPreferredSize(new java.awt.Dimension(100, 36));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        jPanel1.add(stock_nuevo, gridBagConstraints);

        jButton1.setText("Guardar");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        jPanel1.add(jButton1, gridBagConstraints);

        jButton3.setText("Eliminar");
        jButton3.addActionListener(this::jButton3ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        jPanel1.add(jButton3, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.ipadx = 59;
        gridBagConstraints.ipady = 109;
        jPanel2.add(jPanel1, gridBagConstraints);

        jLabel5.setText("Click para seleccionar un registro");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(0, 9, 0, 9);
        jPanel2.add(jLabel5, gridBagConstraints);

        jButton2.setText("Habilitar campo de modificación");
        jButton2.addActionListener(this::jButton2ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        jPanel2.add(jButton2, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1413, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 666, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 666, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int fila = jTable1.getSelectedRow();
        if(fila >= 0){
            idloteSeleccionado = Integer.parseInt(jTable1.getValueAt(fila, 0).toString());
        }
        DAOLotes_inventario_admin conectar = new DAOLotes_inventario_admin();
        conectar.SeleccionarLote(jTable1, id, stock_act);
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (!jTextField2.getText().trim().isEmpty()){
            String texto = jTextField2.getText().trim();

            try {
                int numero = Integer.parseInt(texto);

                if (numero < 0) {
                    JOptionPane.showMessageDialog(null, "Solo se permiten números positivos.");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo números.");
                return;
            }
            DAOLotes_inventario_admin conectar = new DAOLotes_inventario_admin();
            conectar.Listarlotes_díasvencimiento(jTable1, jTextField2);
            jTextField2.setText("");
        }
        else{
            DAOLotes_inventario_admin conectar = new DAOLotes_inventario_admin();
            conectar.Listarlotes(jTable1);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int id_usuario = usuario.getId_usuario();
        if (!stock_nuevo.getText().trim().isEmpty()){
            String texto = stock_nuevo.getText().trim();
            try {
                int numero = Integer.parseInt(texto);

                if (numero < 0) {
                    JOptionPane.showMessageDialog(null, "Solo se permiten números positivos.");
                    return;
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, "Ingrese solo números.");
                return;
            }
            int respuesta = JOptionPane.showConfirmDialog( null, "¿Estas seguro de la modificación?","Confirmación",JOptionPane.YES_NO_OPTION);
            if (respuesta == JOptionPane.YES_OPTION) {
                DAOLotes_inventario_admin conectar = new DAOLotes_inventario_admin();
                conectar.Modificar_stock_lote(id, stock_act,stock_nuevo,id_usuario);
                id.setText("");
                stock_act.setText("");
                stock_nuevo.setText("");
                conectar.Listarlotes(jTable1);
                stock_nuevo.setEnabled(false);
            } else if (respuesta == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(null, "Operación cancelada");
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Ingresa un nuevo stock");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int id_usuario = usuario.getId_usuario();
        if(idloteSeleccionado == 0){
            JOptionPane.showMessageDialog(null,"Seleccione un producto");
            return;
        }
        int respuesta = JOptionPane.showConfirmDialog( null, "¿Estas seguro de eliminar este lote?","Confirmación",JOptionPane.YES_NO_OPTION);
        if (respuesta == JOptionPane.YES_OPTION) {
            DAOLotes_inventario_admin conectar = new DAOLotes_inventario_admin();
            conectar.Eliminar_lote(String.valueOf(idloteSeleccionado),stock_act,id_usuario);
            conectar.Listarlotes(jTable1);
            idloteSeleccionado = 0;        // Reseteamos la variable para que quede limpia
        } else if (respuesta == JOptionPane.NO_OPTION) {
            JOptionPane.showMessageDialog(null, "Operación Cancelada");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        stock_nuevo.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField stock_act;
    private javax.swing.JTextField stock_nuevo;
    // End of variables declaration//GEN-END:variables
}
