/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pantallas_Admin;

import dao.DAOLotes_inventario_admin;
import model.entidad_producto_inventario;

/**
 *
 * @author manue
 */
public class VISUALIZADOR_REGISTROS_X_PRODUCTO extends javax.swing.JPanel {

    /**
     * Creates new form VISUALIZADOR_REGISTROS_X_ACCIÓN
     */
    public VISUALIZADOR_REGISTROS_X_PRODUCTO() {
        initComponents();
        DAOLotes_inventario_admin conectar = new DAOLotes_inventario_admin();
        conectar.llamar_productos(combo_producto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo_producto = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(720, 120));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Selecciona el producto a buscar");
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        combo_producto.setPreferredSize(new java.awt.Dimension(120, 26));
        jPanel1.add(combo_producto, new java.awt.GridBagConstraints());

        jButton1.setText("BUSCAR");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        jPanel1.add(jButton1, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    entidad_producto_inventario producto = (entidad_producto_inventario) combo_producto.getSelectedItem();
    if(producto != null){
        DAOLotes_inventario_admin conectar = new DAOLotes_inventario_admin();
        conectar.ListarRegistros_x_productos(jTable1, producto.getNombre());
    }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<entidad_producto_inventario> combo_producto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
